### ISSUE TITLE
Screen navigation glitches out on logout

### ISSUE THREAD

**Issue by Archit404Error** [cuappdev/eatery-blue-ios#67]
Upon logging out of my GET account, some weird navigation occurs (iPhone 13):

https://github.com/cuappdev/eatery-blue-ios/assets/22649594/994d425c-9eee-4937-89a4-dffe35c00c4a

**Comment by vinnie4k** [comment]
After several hours, I finally figured out the bug.  This was very difficult to replicate because sometimes it worked and sometimes it didn't. I _believe_ I fixed the issue but we will need more people to test.

It was due to a race condition which explains why it was unpredictable. The main thread and a background thread were trying to modify the same resource. Fixed it by making it so one would have to wait for the other.
